#!/usr/bin/env python3
"""Plan, audit, migrate, and roll back role-endpoint routing artifacts."""

from __future__ import annotations

import argparse
import copy
from contextlib import nullcontext
import hashlib
import json
from pathlib import Path
import sqlite3
from typing import Any

from executor_registry import (
    DEFAULT_CONFIG,
    DEFAULT_DATABASE,
    DEFAULT_LEGACY_ALIASES,
    OwnerFileEvidence,
    ROLES,
    RegistryConfig,
    RegistryError,
    attempt_active_uniqueness,
    attempt_schema_is_current,
    canonical_json,
    current_endpoint,
    digest_json,
    ensure_executor_registry_schema,
    immediate_transaction,
    load_registry_config,
    load_legacy_aliases,
    open_registry_database,
    revalidate_registry_inputs,
    utc_now,
    upgrade_attempt_schema,
)


MUTABLE_GITHUB_KINDS = {"issue", "pull_request"}
ACTIONABLE_MESSAGE_STATES = {"PREPARED", "CLAIMED"}
EXECUTABLE_TOPICS = {
    "development.admission",
    "development.recovery_prepare",
    "development.recovery_commit",
    "development.terminal_closeout",
    "sre.admission",
}


class ReviewedAliases(list[dict[str, str]]):
    """List-compatible alias data carrying its reviewed descriptor evidence."""

    def __init__(
        self,
        values: list[dict[str, str]],
        *,
        source_evidence: OwnerFileEvidence,
    ) -> None:
        super().__init__(values)
        self.source_evidence = source_evidence


def load_legacy_alias_fixture(path: Path) -> tuple[ReviewedAliases, str]:
    try:
        loaded = load_legacy_aliases(path)
    except RegistryError as exc:
        raise RegistryError("LEGACY_ALIAS_FIXTURE_INVALID") from exc
    normalized = [
        {"alias": alias, "role": role}
        for alias, role in loaded.aliases.items()
    ]
    normalized.sort(key=lambda entry: entry["role"])
    return (
        ReviewedAliases(normalized, source_evidence=loaded.source_evidence),
        loaded.source_sha256,
    )


def _legacy_occurrences(value: Any, aliases: set[str], path: str = "$") -> list[dict[str, str]]:
    found: list[dict[str, str]] = []
    if isinstance(value, dict):
        for key, child in value.items():
            found.extend(_legacy_occurrences(child, aliases, f"{path}.{key}"))
    elif isinstance(value, list):
        for index, child in enumerate(value):
            found.extend(_legacy_occurrences(child, aliases, f"{path}[{index}]"))
    elif isinstance(value, str):
        # The migration plan is digest-bound and may be generated by a fresh
        # Python process.  Never let per-process set hash randomization change
        # occurrence ordering (and therefore the reviewed plan digest).
        for alias in sorted(aliases):
            if alias in value:
                found.append({"path": path, "alias": alias})
    return found


def _github_inventory_hints(
    connection: sqlite3.Connection, aliases: set[str]
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    hints: list[dict[str, Any]] = []
    immutable_history: list[dict[str, Any]] = []
    tables = {
        row[0]
        for row in connection.execute(
            "SELECT name FROM sqlite_master WHERE type='table'"
        ).fetchall()
    }
    if not {"github_current", "github_snapshots"}.issubset(tables):
        return hints, immutable_history
    rows = connection.execute(
        """
        SELECT current.repository, current.object_kind, current.object_number,
               current.payload_sha256, current.source_updated_at, snapshot.payload_json
        FROM github_current current
        JOIN github_snapshots snapshot
          ON snapshot.repository=current.repository
         AND snapshot.object_kind=current.object_kind
         AND snapshot.object_number=current.object_number
         AND snapshot.payload_sha256=current.payload_sha256
        ORDER BY current.repository, current.object_kind, current.object_number
        """
    ).fetchall()
    for row in rows:
        if row["object_kind"] not in MUTABLE_GITHUB_KINDS:
            continue
        try:
            payload = json.loads(row["payload_json"])
        except json.JSONDecodeError:
            immutable_history.append({
                "repository": row["repository"],
                "object_kind": row["object_kind"],
                "object_number": int(row["object_number"]),
                "error": "CURRENT_GITHUB_PAYLOAD_INVALID",
            })
            continue
        body = payload.get("body") if isinstance(payload, dict) else None
        if isinstance(body, str):
            body_occurrences = _legacy_occurrences(body, aliases, "$.body")
            if body_occurrences:
                hints.append({
                    "repository": row["repository"],
                    "object_kind": row["object_kind"],
                    "object_number": int(row["object_number"]),
                    "source_payload_sha256": row["payload_sha256"],
                    "source_updated_at_sha256": hashlib.sha256(
                        str(row["source_updated_at"]).encode("utf-8")
                    ).hexdigest(),
                    "body_sha256": hashlib.sha256(body.encode("utf-8")).hexdigest(),
                    "occurrence_manifest_sha256": digest_json(body_occurrences),
                    "occurrence_count": len(body_occurrences),
                })
        comments = payload.get("comments") if isinstance(payload, dict) else None
        comment_occurrences = _legacy_occurrences(comments, aliases, "$.comments")
        if comment_occurrences:
            immutable_history.append({
                "repository": row["repository"],
                "object_kind": row["object_kind"],
                "object_number": int(row["object_number"]),
                "source_payload_sha256": row["payload_sha256"],
                "occurrence_manifest_sha256": digest_json(comment_occurrences),
                "occurrence_count": len(comment_occurrences),
                "disposition": "IMMUTABLE_PROVENANCE_NO_REWRITE",
            })
    return hints, immutable_history


def _table_exists(connection: sqlite3.Connection, table: str) -> bool:
    return connection.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (table,)
    ).fetchone() is not None


def _broker_cutover_blockers(
    connection: sqlite3.Connection,
    endpoints: list[dict[str, Any]],
    pointer_changes: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Inventory work a readiness-only endpoint cannot execute after cutover."""

    by_role = {endpoint["role"]: endpoint for endpoint in endpoints}
    blockers: list[dict[str, Any]] = []
    for change in pointer_changes:
        endpoint = by_role[change["role"]]
        before = change["before_endpoint_id"]
        if (
            endpoint.get("execution_protocol") != "readiness/v1"
            or before == change["after_endpoint_id"]
        ):
            continue
        blockers.append(
            {
                "role": change["role"],
                "endpoint_id": change["after_endpoint_id"],
                "kind": "credential_transport",
                "key": "ATTEMPT_BOUND_RESPONSES_PROXY_NOT_IMPLEMENTED",
            }
        )
        if before is None:
            continue
        item_columns = {
            str(row[1])
            for row in connection.execute("PRAGMA table_info(coordination_items)")
        } if _table_exists(connection, "coordination_items") else set()
        item_query = (
            """
            SELECT repository || '#issue-' || issue_number AS key
            FROM coordination_items
            WHERE accountable_session_id=?
              AND (allocation_class!='NONE' OR status IN
                   ('READY','ACTIVE','ACTIVE_FENCED','MONITOR'))
            ORDER BY repository, issue_number
            """
            if {"allocation_class", "status"}.issubset(item_columns)
            else """
            SELECT repository || '#issue-' || issue_number AS key
            FROM coordination_items WHERE accountable_session_id=?
            ORDER BY repository, issue_number
            """
        )
        inventories = (
            (
                "coordination_messages",
                "message",
                """
                SELECT CAST(id AS TEXT) AS key FROM coordination_messages
                WHERE recipient_session_id=? AND state IN ('PREPARED','CLAIMED')
                ORDER BY id
                """,
            ),
            (
                "coordination_items",
                "item",
                item_query,
            ),
            (
                "coordination_terminal_watches",
                "terminal_watch",
                """
                SELECT watch_key AS key FROM coordination_terminal_watches
                WHERE accountable_session_id=? AND state='ACTIVE'
                ORDER BY watch_key
                """,
            ),
            (
                "hosted_operations",
                "hosted_operation",
                """
                SELECT CAST(id AS TEXT) AS key FROM hosted_operations
                WHERE recipient_session_id=?
                  AND state IN ('WAITING','PREPARED','CLAIMED')
                ORDER BY id
                """,
            ),
            (
                "executor_attempts",
                "attempt",
                """
                SELECT attempt_id AS key FROM executor_attempts
                WHERE endpoint_id=? AND state IN ('RESERVED','LAUNCHING','RUNNING')
                ORDER BY created_at, attempt_id
                """,
            ),
        )
        for table, kind, query in inventories:
            if not _table_exists(connection, table):
                continue
            for row in connection.execute(query, (before,)).fetchall():
                blockers.append(
                    {
                        "role": change["role"],
                        "endpoint_id": before,
                        "kind": kind,
                        "key": str(row["key"]),
                    }
                )
    return blockers


def build_plan(
    connection: sqlite3.Connection,
    config: RegistryConfig,
    aliases: list[dict[str, str]],
    *,
    alias_fixture_sha256: str,
) -> dict[str, Any]:
    return _build_plan_from_inputs(
        connection,
        config_sha256=config.source_sha256,
        endpoints=[config.roles[role].payload for role in ROLES],
        aliases=aliases,
        alias_fixture_sha256=alias_fixture_sha256,
    )


def _build_plan_from_inputs(
    connection: sqlite3.Connection,
    *,
    config_sha256: str,
    endpoints: list[dict[str, Any]],
    aliases: list[dict[str, str]],
    alias_fixture_sha256: str,
) -> dict[str, Any]:
    endpoint_by_role = {
        endpoint["role"]: endpoint["endpoint_id"] for endpoint in endpoints
    }
    endpoint_by_alias = {
        entry["alias"]: endpoint_by_role[entry["role"]] for entry in aliases
    }
    pointer_changes: list[dict[str, Any]] = []
    has_current_pointers = _table_exists(
        connection, "executor_role_endpoint_current"
    )
    for role in ROLES:
        row = (
            connection.execute(
                "SELECT endpoint_id, pointer_version FROM executor_role_endpoint_current WHERE role=?",
                (role,),
            ).fetchone()
            if has_current_pointers
            else None
        )
        pointer_changes.append({
            "role": role,
            "before_endpoint_id": None if row is None else row["endpoint_id"],
            "before_pointer_version": 0 if row is None else int(row["pointer_version"]),
            "after_endpoint_id": endpoint_by_role[role],
            "after_pointer_version": 1 if row is None else int(row["pointer_version"]) + (
                row["endpoint_id"] != endpoint_by_role[role]
            ),
        })
    item_changes: list[dict[str, Any]] = []
    if _table_exists(connection, "coordination_items"):
        for row in connection.execute(
            "SELECT repository, issue_number, accountable_session_id, version FROM coordination_items ORDER BY repository, issue_number"
        ).fetchall():
            identity = row["accountable_session_id"]
            if identity in endpoint_by_alias:
                item_changes.append({
                    "repository": row["repository"],
                    "issue_number": int(row["issue_number"]),
                    "before_identity": identity,
                    "after_identity": endpoint_by_alias[identity],
                    "before_version": int(row["version"]),
                    "after_version": int(row["version"]) + 1,
                })
    watch_changes: list[dict[str, Any]] = []
    if _table_exists(connection, "coordination_terminal_watches"):
        for row in connection.execute(
            """
            SELECT watch_key, accountable_session_id, state, updated_at
            FROM coordination_terminal_watches
            WHERE state='ACTIVE' ORDER BY watch_key
            """
        ).fetchall():
            identity = row["accountable_session_id"]
            if identity in endpoint_by_alias:
                watch_changes.append({
                    "watch_key": row["watch_key"],
                    "before_identity": identity,
                    "after_identity": endpoint_by_alias[identity],
                    "expected_state": row["state"],
                    "expected_updated_at": row["updated_at"],
                })
    immutable_messages: list[dict[str, Any]] = []
    if _table_exists(connection, "coordination_messages"):
        for row in connection.execute(
            """
            SELECT id, recipient_session_id, topic, state, payload_sha256
            FROM coordination_messages ORDER BY id
            """
        ).fetchall():
            if row["recipient_session_id"] in endpoint_by_alias:
                immutable_messages.append({
                    "message_id": int(row["id"]),
                    "legacy_alias": row["recipient_session_id"],
                    "endpoint_id": endpoint_by_alias[row["recipient_session_id"]],
                    "topic": row["topic"],
                    "state": row["state"],
                    "payload_sha256": row["payload_sha256"],
                    "disposition": "IMMUTABLE_PROVENANCE_ALIAS_ROUTE",
                })
    github_hints, github_comments = _github_inventory_hints(
        connection, set(endpoint_by_alias)
    )
    attempts_present = _table_exists(connection, "executor_attempts")
    schema_current = (
        attempts_present and attempt_schema_is_current(connection)
    )
    active_uniqueness = attempt_active_uniqueness(connection)
    plan = {
        "kind": "TWINFINITY_ROLE_ENDPOINT_MIGRATION_V1",
        "config_sha256": config_sha256,
        "alias_fixture_sha256": alias_fixture_sha256,
        "endpoints": copy.deepcopy(endpoints),
        "aliases": aliases,
        "attempt_schema_upgrade": (
            attempts_present and not schema_current
        ),
        "attempt_active_uniqueness": (
            "ROLE_TARGET" if schema_current or not attempts_present
            else active_uniqueness
        ),
        "pointer_changes": pointer_changes,
        "broker_cutover_blockers": _broker_cutover_blockers(
            connection, endpoints, pointer_changes
        ),
        "item_changes": item_changes,
        "watch_changes": watch_changes,
        "immutable_message_aliases": immutable_messages,
        "github_routing_inventory_hints": github_hints,
        "github_comment_history": github_comments,
        "github_mutation_performed": False,
    }
    plan["plan_sha256"] = digest_json(plan)
    return plan


def _verify_or_insert_endpoint(
    connection: sqlite3.Connection, endpoint: dict[str, Any], now: str
) -> None:
    payload = copy.deepcopy(endpoint)
    role = payload.pop("role")
    config_payload = {"role": role, **payload}
    config_sha256 = digest_json(config_payload)
    current = connection.execute(
        "SELECT * FROM executor_role_endpoints WHERE endpoint_id=?",
        (endpoint["endpoint_id"],),
    ).fetchone()
    expected = {
        "endpoint_id": endpoint["endpoint_id"],
        "role": role,
        "version": endpoint["version"],
        "executor_profile": endpoint["executor_profile"],
        "codex_profile": endpoint["codex_profile"],
        "config_sha256": config_sha256,
        "config_json": canonical_json(config_payload),
        "command_json": canonical_json(endpoint["command_prefix"]),
    }
    if current is not None:
        if any(current[key] != value for key, value in expected.items()):
            raise RegistryError("EXECUTOR_ENDPOINT_IMMUTABLE_CONFLICT")
        return
    connection.execute(
        """
        INSERT INTO executor_role_endpoints(
            endpoint_id, role, version, executor_profile, codex_profile,
            config_sha256, config_json, command_json, created_at
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        tuple(expected[key] for key in (
            "endpoint_id", "role", "version", "executor_profile", "codex_profile",
            "config_sha256", "config_json", "command_json"
        )) + (now,),
    )


def apply_plan(
    connection: sqlite3.Connection,
    *,
    plan: dict[str, Any],
    operation_key: str,
    expected_plan_sha256: str,
    now: str,
    _within_immediate_transaction: bool = False,
) -> dict[str, Any]:
    if not operation_key or plan.get("plan_sha256") != expected_plan_sha256:
        raise RegistryError("REGISTRY_MIGRATION_PLAN_MISMATCH")
    if digest_json({key: value for key, value in plan.items() if key != "plan_sha256"}) != expected_plan_sha256:
        raise RegistryError("REGISTRY_MIGRATION_PLAN_MISMATCH")
    if _within_immediate_transaction and not connection.in_transaction:
        raise RegistryError("REGISTRY_MIGRATION_TRANSACTION_REQUIRED")
    change_id = hashlib.sha256(
        f"{operation_key}\0{expected_plan_sha256}".encode("utf-8")
    ).hexdigest()
    transaction = (
        nullcontext()
        if _within_immediate_transaction
        else immediate_transaction(connection)
    )
    with transaction:
        prior = (
            connection.execute(
                "SELECT * FROM executor_registry_changes WHERE operation_key=?",
                (operation_key,),
            ).fetchone()
            if _table_exists(connection, "executor_registry_changes")
            else None
        )
        if prior is not None:
            if prior["change_id"] != change_id or prior["state"] != "APPLIED":
                raise RegistryError("REGISTRY_MIGRATION_IDEMPOTENCY_CONFLICT")
            return dict(prior)
        plan = _build_plan_from_inputs(
            connection,
            config_sha256=plan["config_sha256"],
            endpoints=plan["endpoints"],
            aliases=plan["aliases"],
            alias_fixture_sha256=plan["alias_fixture_sha256"],
        )
        if plan["plan_sha256"] != expected_plan_sha256:
            raise RegistryError("REGISTRY_MIGRATION_PLAN_MISMATCH")
        actionable_broker_blockers = [
            blocker
            for blocker in plan.get("broker_cutover_blockers", [])
            if blocker["kind"] != "credential_transport"
        ]
        if actionable_broker_blockers:
            raise RegistryError("REGISTRY_BROKER_CUTOVER_ACTIONABLE_WORK")
        if plan.get("broker_cutover_blockers"):
            raise RegistryError("REGISTRY_BROKER_CREDENTIAL_TRANSPORT_REQUIRED")
        ensure_executor_registry_schema(connection)
        schema_current = attempt_schema_is_current(connection)
        if bool(plan.get("attempt_schema_upgrade")) == schema_current:
            raise RegistryError("EXECUTOR_ATTEMPT_SCHEMA_DRIFT")
        expected_uniqueness = attempt_active_uniqueness(connection)
        if plan.get("attempt_active_uniqueness") != expected_uniqueness:
            raise RegistryError("EXECUTOR_ATTEMPT_SCHEMA_DRIFT")
        if plan["attempt_schema_upgrade"]:
            upgrade_attempt_schema(connection)
        for endpoint in plan["endpoints"]:
            _verify_or_insert_endpoint(connection, endpoint, now)
        endpoint_by_role = {
            endpoint["role"]: endpoint["endpoint_id"] for endpoint in plan["endpoints"]
        }
        for alias in plan["aliases"]:
            endpoint_id = endpoint_by_role[alias["role"]]
            current = connection.execute(
                """
                SELECT alias.role, alias.endpoint_id, endpoint.role AS endpoint_role
                FROM executor_role_endpoint_aliases alias
                JOIN executor_role_endpoints endpoint
                  ON endpoint.endpoint_id=alias.endpoint_id
                WHERE alias.alias=?
                """,
                (alias["alias"],),
            ).fetchone()
            if current is None:
                connection.execute(
                    "INSERT INTO executor_role_endpoint_aliases(alias, role, endpoint_id, source, created_at) VALUES (?, ?, ?, 'legacy-fixture', ?)",
                    (alias["alias"], alias["role"], endpoint_id, now),
                )
            elif (
                current["role"] != alias["role"]
                or current["endpoint_role"] != alias["role"]
            ):
                raise RegistryError("EXECUTOR_ALIAS_IMMUTABLE_CONFLICT")
        for change in plan["pointer_changes"]:
            current = connection.execute(
                "SELECT endpoint_id, pointer_version FROM executor_role_endpoint_current WHERE role=?",
                (change["role"],),
            ).fetchone()
            actual_endpoint = None if current is None else current["endpoint_id"]
            actual_version = 0 if current is None else int(current["pointer_version"])
            if (
                actual_endpoint != change["before_endpoint_id"]
                or actual_version != change["before_pointer_version"]
            ):
                raise RegistryError("REGISTRY_POINTER_VERSION_CONFLICT")
            if current is None:
                connection.execute(
                    "INSERT INTO executor_role_endpoint_current(role, endpoint_id, pointer_version, updated_at) VALUES (?, ?, 1, ?)",
                    (change["role"], change["after_endpoint_id"], now),
                )
            elif current["endpoint_id"] != change["after_endpoint_id"]:
                cursor = connection.execute(
                    """
                    UPDATE executor_role_endpoint_current
                    SET endpoint_id=?, pointer_version=pointer_version+1, updated_at=?
                    WHERE role=? AND endpoint_id=? AND pointer_version=?
                    """,
                    (
                        change["after_endpoint_id"], now, change["role"],
                        change["before_endpoint_id"], change["before_pointer_version"],
                    ),
                )
                if cursor.rowcount != 1:
                    raise RegistryError("REGISTRY_POINTER_VERSION_CONFLICT")
        for change in plan["item_changes"]:
            cursor = connection.execute(
                """
                UPDATE coordination_items
                SET accountable_session_id=?, version=version+1, updated_at=?
                WHERE repository=? AND issue_number=?
                  AND accountable_session_id=? AND version=?
                """,
                (
                    change["after_identity"], now, change["repository"],
                    change["issue_number"], change["before_identity"],
                    change["before_version"],
                ),
            )
            if cursor.rowcount != 1:
                raise RegistryError("REGISTRY_ITEM_VERSION_CONFLICT")
        for change in plan["watch_changes"]:
            cursor = connection.execute(
                """
                UPDATE coordination_terminal_watches
                SET accountable_session_id=?, updated_at=?
                WHERE watch_key=? AND accountable_session_id=?
                  AND state=? AND updated_at=?
                """,
                (
                    change["after_identity"], now, change["watch_key"],
                    change["before_identity"], change["expected_state"],
                    change["expected_updated_at"],
                ),
            )
            if cursor.rowcount != 1:
                raise RegistryError("REGISTRY_WATCH_VERSION_CONFLICT")
        after = {
            "pointers": [
                dict(row) for row in connection.execute(
                    "SELECT role, endpoint_id, pointer_version FROM executor_role_endpoint_current ORDER BY role"
                ).fetchall()
            ],
            "items": [
                dict(row) for row in connection.execute(
                    "SELECT repository, issue_number, accountable_session_id, version FROM coordination_items ORDER BY repository, issue_number"
                ).fetchall()
            ] if _table_exists(connection, "coordination_items") else [],
            "watches": [
                dict(row) for row in connection.execute(
                    "SELECT watch_key, accountable_session_id, state, updated_at FROM coordination_terminal_watches WHERE state='ACTIVE' ORDER BY watch_key"
                ).fetchall()
            ] if _table_exists(connection, "coordination_terminal_watches") else [],
        }
        connection.execute(
            """
            INSERT INTO executor_registry_changes(
                change_id, operation_key, config_sha256, before_state_sha256,
                before_state_json, after_state_sha256, after_state_json,
                state, version, created_at, updated_at
            ) VALUES (?, ?, ?, ?, ?, ?, ?, 'APPLIED', 1, ?, ?)
            """,
            (
                change_id,
                operation_key,
                plan["config_sha256"],
                expected_plan_sha256,
                canonical_json(plan),
                digest_json(after),
                canonical_json(after),
                now,
                now,
            ),
        )
        result = connection.execute(
            "SELECT * FROM executor_registry_changes WHERE change_id=?", (change_id,)
        ).fetchone()
    return dict(result)


def migrate_plan(
    connection: sqlite3.Connection,
    *,
    config: RegistryConfig,
    aliases: list[dict[str, str]],
    alias_fixture_sha256: str,
    operation_key: str,
    expected_plan_sha256: str,
    now: str,
) -> dict[str, Any]:
    """Recompute, validate, and apply one reviewed plan under one write lock."""

    if not operation_key:
        raise RegistryError("REGISTRY_MIGRATION_PLAN_MISMATCH")
    if (
        not isinstance(aliases, ReviewedAliases)
        or aliases.source_evidence.sha256 != alias_fixture_sha256
    ):
        raise RegistryError("REGISTRY_MIGRATION_INPUT_EVIDENCE_REQUIRED")
    with immediate_transaction(connection):
        # These files define the reviewed migration.  Re-read all of them from
        # owner-safe descriptors and require exact descriptor metadata and
        # content digests while the SQLite write lock is held.  This occurs
        # before replay, schema installation, or any row mutation.
        transaction_config = revalidate_registry_inputs(config)
        transaction_alias_source = load_legacy_aliases(
            Path(aliases.source_evidence.path)
        )
        transaction_aliases = [
            {"alias": alias, "role": role}
            for alias, role in transaction_alias_source.aliases.items()
        ]
        transaction_aliases.sort(key=lambda entry: entry["role"])
        if (
            transaction_alias_source.source_evidence != aliases.source_evidence
            or transaction_alias_source.source_sha256 != alias_fixture_sha256
            or transaction_aliases != list(aliases)
        ):
            raise RegistryError("LEGACY_ALIAS_FILE_DRIFT")
        prior = replay_applied_change(
            connection,
            operation_key=operation_key,
            expected_plan_sha256=expected_plan_sha256,
            config_sha256=transaction_config.source_sha256,
            alias_fixture_sha256=alias_fixture_sha256,
        )
        if prior is not None:
            return prior
        plan = build_plan(
            connection,
            transaction_config,
            transaction_aliases,
            alias_fixture_sha256=alias_fixture_sha256,
        )
        return apply_plan(
            connection,
            plan=plan,
            operation_key=operation_key,
            expected_plan_sha256=expected_plan_sha256,
            now=now,
            _within_immediate_transaction=True,
        )


def replay_applied_change(
    connection: sqlite3.Connection,
    *,
    operation_key: str,
    expected_plan_sha256: str,
    config_sha256: str,
    alias_fixture_sha256: str,
) -> dict[str, Any] | None:
    """Return an exact already-applied migration without rebuilding a drifted plan."""

    if not operation_key:
        raise RegistryError("REGISTRY_MIGRATION_PLAN_MISMATCH")
    if not _table_exists(connection, "executor_registry_changes"):
        return None
    prior = connection.execute(
        "SELECT * FROM executor_registry_changes WHERE operation_key=?",
        (operation_key,),
    ).fetchone()
    if prior is None:
        return None
    expected_change_id = hashlib.sha256(
        f"{operation_key}\0{expected_plan_sha256}".encode("utf-8")
    ).hexdigest()
    try:
        original_plan = json.loads(prior["before_state_json"])
    except json.JSONDecodeError as exc:
        raise RegistryError("REGISTRY_MIGRATION_IDEMPOTENCY_CONFLICT") from exc
    if (
        prior["change_id"] != expected_change_id
        or prior["state"] != "APPLIED"
        or prior["config_sha256"] != config_sha256
        or original_plan.get("plan_sha256") != expected_plan_sha256
        or original_plan.get("alias_fixture_sha256") != alias_fixture_sha256
    ):
        raise RegistryError("REGISTRY_MIGRATION_IDEMPOTENCY_CONFLICT")
    return dict(prior)


def rollback_change(
    connection: sqlite3.Connection,
    *,
    change_id: str,
    expected_version: int,
    now: str,
) -> dict[str, Any]:
    ensure_executor_registry_schema(connection)
    with immediate_transaction(connection):
        change = connection.execute(
            "SELECT * FROM executor_registry_changes WHERE change_id=?", (change_id,)
        ).fetchone()
        if change is None:
            raise RegistryError("REGISTRY_CHANGE_NOT_FOUND")
        if change["state"] == "ROLLED_BACK":
            if int(change["version"]) != expected_version + 1:
                raise RegistryError("REGISTRY_CHANGE_VERSION_CONFLICT")
            return dict(change)
        if change["state"] != "APPLIED" or int(change["version"]) != expected_version:
            raise RegistryError("REGISTRY_CHANGE_VERSION_CONFLICT")
        plan = json.loads(change["before_state_json"])
        after_state = json.loads(change["after_state_json"])
        after_watches = {
            watch["watch_key"]: watch for watch in after_state.get("watches", [])
        }
        for item in plan["item_changes"]:
            cursor = connection.execute(
                """
                UPDATE coordination_items
                SET accountable_session_id=?, version=version+1, updated_at=?
                WHERE repository=? AND issue_number=?
                  AND accountable_session_id=? AND version=?
                """,
                (
                    item["before_identity"], now, item["repository"],
                    item["issue_number"], item["after_identity"], item["after_version"],
                ),
            )
            if cursor.rowcount != 1:
                raise RegistryError("REGISTRY_ROLLBACK_ITEM_CONFLICT")
        for watch in plan["watch_changes"]:
            applied_watch = after_watches.get(watch["watch_key"])
            if (
                applied_watch is None
                or applied_watch.get("accountable_session_id") != watch["after_identity"]
                or applied_watch.get("state") != watch["expected_state"]
                or not isinstance(applied_watch.get("updated_at"), str)
            ):
                raise RegistryError("REGISTRY_ROLLBACK_WATCH_CONFLICT")
            cursor = connection.execute(
                """
                UPDATE coordination_terminal_watches
                SET accountable_session_id=?, updated_at=?
                WHERE watch_key=? AND accountable_session_id=? AND state=?
                  AND updated_at=?
                """,
                (
                    watch["before_identity"], now, watch["watch_key"],
                    watch["after_identity"], watch["expected_state"],
                    applied_watch["updated_at"],
                ),
            )
            if cursor.rowcount != 1:
                raise RegistryError("REGISTRY_ROLLBACK_WATCH_CONFLICT")
        for pointer in plan["pointer_changes"]:
            current = connection.execute(
                "SELECT endpoint_id, pointer_version FROM executor_role_endpoint_current WHERE role=?",
                (pointer["role"],),
            ).fetchone()
            if (
                current is None
                or current["endpoint_id"] != pointer["after_endpoint_id"]
                or int(current["pointer_version"]) != pointer["after_pointer_version"]
            ):
                raise RegistryError("REGISTRY_ROLLBACK_POINTER_CONFLICT")
            if pointer["before_endpoint_id"] is None:
                connection.execute(
                    "DELETE FROM executor_role_endpoint_current WHERE role=? AND pointer_version=?",
                    (pointer["role"], pointer["after_pointer_version"]),
                )
            elif pointer["before_endpoint_id"] != pointer["after_endpoint_id"]:
                connection.execute(
                    """
                    UPDATE executor_role_endpoint_current
                    SET endpoint_id=?, pointer_version=pointer_version+1, updated_at=?
                    WHERE role=? AND pointer_version=?
                    """,
                    (
                        pointer["before_endpoint_id"], now, pointer["role"],
                        pointer["after_pointer_version"],
                    ),
                )
        cursor = connection.execute(
            """
            UPDATE executor_registry_changes
            SET state='ROLLED_BACK', version=version+1, updated_at=?
            WHERE change_id=? AND state='APPLIED' AND version=?
            """,
            (now, change_id, expected_version),
        )
        if cursor.rowcount != 1:
            raise RegistryError("REGISTRY_CHANGE_VERSION_CONFLICT")
        result = connection.execute(
            "SELECT * FROM executor_registry_changes WHERE change_id=?", (change_id,)
        ).fetchone()
    return dict(result)


def audit_plan(plan: dict[str, Any]) -> dict[str, Any]:
    blockers: list[str] = []
    if (
        plan.get("attempt_schema_upgrade")
        or plan.get("attempt_active_uniqueness") != "ROLE_TARGET"
    ):
        blockers.append("EXECUTOR_ATTEMPT_SCHEMA_MIGRATION_REQUIRED")
    if any(
        change["before_endpoint_id"] != change["after_endpoint_id"]
        for change in plan["pointer_changes"]
    ):
        blockers.append("CURRENT_POINTER_DRIFT")
    if plan["item_changes"] or plan["watch_changes"]:
        blockers.append("MUTABLE_LOCAL_ROUTING_DRIFT")
    if any(
        message["state"] in ACTIONABLE_MESSAGE_STATES
        and message["topic"] in EXECUTABLE_TOPICS
        for message in plan["immutable_message_aliases"]
    ):
        blockers.append("LEGACY_EXECUTABLE_MESSAGE_ACTIVE")
    if plan["github_routing_inventory_hints"]:
        blockers.append("ROUTING_DEPRECATION_INVENTORY_REQUIRED")
    if any(
        blocker["kind"] != "credential_transport"
        for blocker in plan.get("broker_cutover_blockers", [])
    ):
        blockers.append("REGISTRY_BROKER_CUTOVER_ACTIONABLE_WORK")
    if any(
        blocker["kind"] == "credential_transport"
        for blocker in plan.get("broker_cutover_blockers", [])
    ):
        blockers.append("REGISTRY_BROKER_CREDENTIAL_TRANSPORT_REQUIRED")
    return {
        "phase": "PASS" if not blockers else "HOLD",
        "plan_sha256": plan["plan_sha256"],
        "blockers": sorted(set(blockers)),
        "github_mutation_performed": False,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument(
        "--legacy-alias-file",
        "--legacy-alias-fixture",
        dest="legacy_alias_file",
        type=Path,
        default=DEFAULT_LEGACY_ALIASES,
        help="strict reviewed alias data (defaults to the installed production file)",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)
    subparsers.add_parser("dry-run")
    subparsers.add_parser("audit")
    migrate = subparsers.add_parser("migrate")
    migrate.add_argument("--operation-key", required=True)
    migrate.add_argument("--expected-plan-sha256", required=True)
    rollback = subparsers.add_parser("rollback")
    rollback.add_argument("--change-id", required=True)
    rollback.add_argument("--expected-version", required=True, type=int)
    args = parser.parse_args()
    connection: sqlite3.Connection | None = None
    try:
        config = load_registry_config(
            args.config, profile_validation_scope="catalog"
        )
        aliases, alias_sha = load_legacy_alias_fixture(args.legacy_alias_file)
        connection = open_registry_database(
            DEFAULT_DATABASE,
            read_only=args.command in {"dry-run", "audit"},
            initialize_schema=args.command != "migrate",
        )
        plan: dict[str, Any] | None = None
        if args.command in {"dry-run", "audit"}:
            plan = build_plan(
                connection, config, aliases, alias_fixture_sha256=alias_sha
            )
        if args.command == "dry-run":
            assert plan is not None
            print(canonical_json(plan))
            return 0
        if args.command == "audit":
            assert plan is not None
            result = audit_plan(plan)
            print(canonical_json(result))
            return 0 if result["phase"] == "PASS" else 1
        if args.command == "migrate":
            result = migrate_plan(
                connection,
                config=config,
                aliases=aliases,
                alias_fixture_sha256=alias_sha,
                operation_key=args.operation_key,
                expected_plan_sha256=args.expected_plan_sha256,
                now=utc_now(),
            )
        else:
            result = rollback_change(
                connection,
                change_id=args.change_id,
                expected_version=args.expected_version,
                now=utc_now(),
            )
        print(canonical_json({
            "phase": "PASS",
            "change_id": result["change_id"],
            "state": result["state"],
            "version": result["version"],
            "github_mutation_performed": False,
        }))
        return 0
    except (OSError, RegistryError, sqlite3.Error) as exc:
        error = str(exc) if isinstance(exc, RegistryError) else "REGISTRY_RECONCILIATION_FAILED"
        print(canonical_json({"phase": "HOLD", "error": error, "github_mutation_performed": False}))
        return 1
    finally:
        if connection is not None:
            connection.close()


if __name__ == "__main__":
    raise SystemExit(main())
